config/routes.rb
Rails.application.routes.draw do
  resources :users
  
  resource :session, only:[:new, :create, :session_path, :destroy]
  resources :hospitals

  resources :pairings

end

app/models/hospital.rb
class Hospital
  include Mongoid::Document
   
  field :name, type: String 
  field :practice_field, type: String
  field :location, type: String
  field :benefit, type: String 
  
  has_many :pairings

 end 



# 	# Bring back an array of hospitals
#   def hospitals
#   	Hospital.find hospital_ids
#   end

# #   # Bring back an array of all hospital IDs
#   def hospital_ids
#   	self.user_hospitals.map(&:hospital_id)
#   end

# #   # Update hospital IDs for this user
#   def hospital_ids=(list)
#   	self.user_hospitals.destroy
#   	list.each do |hospital_id|
#   		unless hospital_id.blank?
#   			self.user_hospitals.create(hospital_id: hospital_id)
#   		end
#   	end
#   
# end
#---------------------------------------------------

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  validates_presence_of :name, :email
  
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String 

  has_secure_password
  # field :is_admin, type: Boolean

	has_many :pairings

# accepts_nested_attributes_for :hospitals 
# validates :name, presence: true

#   validates :email, presence: true
#   validates_uniqueness_of :email

end 


# def pairings
#     Pairings.find pairing_ids
#   end

#  def pairing_ids
#     ret = []
#     self.user_pairings.each do |p|
#       ret << p.pairing_id if p.pairing_id

# # def pairing_ids
# # 	self.user_pairings.map (&:hospital_id)
# # end
#     end
#   

#   def pairing_ids=(list)
#     self.user_pairings.destroy
#     list.each do |pairing_id|
#       self.user_pairings.create(pairing_id: pairing_id)
#     end
#   end

  

app/controllers/users_controller.rb
class UsersController < ApplicationController

# only: [:index, :show, :edit, :update, :destroy]

# before_action :signed_in_user, only: [:edit, :update]

  def index
    @users =User.all
  end
# ';'
  # GET /users/1
  # GET /users/1.json
    def show
      @user = User.find(params[:id]) 
    end

    # GET /users/new
    def new
      @user = User.new
      @is_signup = true
    end

  # GET /users/1/edit
    def edit
      @user = User.find(params[:id])
    end
    

  # POST /uers
  # POST /users.json
    def create
      @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
      if @user.save
        @current_user = @user
        session[:user_id] = @user.id
        redirect_to users_path
      else
        render 'new'
      end
    end

    

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
    def update
      @user = User.find(params[:id])
        if @user.update_attributes(params.require(:user).permit(:name, :email, :password,  :password_confirmation))
          redirect_to users_path
        else
          render 'edit' 
         end
      end
end 


  # private

  #   def user_params
  #     params.require(:user).permit(:name, :email, :password, :password_confirmation)
  #     pairing_ids [],
  #     hospitals_attributes: [:id, :name, :location, :practice_field, :benefit]
  #   end 
  # end 


 
  #   end














#     # Before filters

#     def signed_in_user
#       redirect_to signin_url, notice: "Please sign in." unless signed_in?
#     end
# end

  # DELETE /users/1
  # DELETE /users/1.json
  

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_user
  #     @user = User.find(params[:id])
  #   end

  # def destroy
  #       @user = User.find(params[:id])
  #       @user.is_active = false
  #       @user.save
  #       redirect_to users_path
  #   end

  #   def reactivate 
  #     @user =User.find(params[:id])
  #     # @user.is_active = true 
  #   end   



    # Never trust parameters from the scary internet, only allow the white list through.
#     def user_params
#       params.require(:user).permit(:option, :branch_of_medicine, :review, :doc_preference)
#     end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	Name: <%= f.text_field :name %>
	Email: <%= f.text_field :email %>
	Password: <%= f.password_field :password %>
	<br />

Save it <%= f.collection_check_boxes :pairing_ids, Pairing.all, :id, :name %>

	<br />

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for @user do |f| %>

  Name <%= f.text_field :name, placeholder: "edit your user name" %><br />
  Email <%= f.text_field :email, placeholder: "edit your email address" %><br />

  <%= f.password_field :password, placeholder: "your password" %><br />
  <%= f.password_field :password_confirmation, placeholder: "re-enter your password" %>

  

  <%= f.submit "Edit User", class: "btn btn-primary btn-large" %>

<% end %>



<%= link_to 'Go to your Check Box', users_path %>
<%= link_to 'Go back to the main page', users_path %>

app/views/users/index.html.erb
<h1>Welcome to Care Access!</h1>

<p>This website is designated to provide blabla. In order to access, please log in or sign up for the site </P>



<% if current_user %> 

<p>If you are a new user, please click 'Sign up' button above</p>

<p>In order to access to this site, please click 'Log In' button above</p> 




<%= link_to 'Check Box', pairings_path %>


<% else %>


<% end %>

<address>
  <strong>Twitter, Inc.</strong><br>
  795 Folsom Ave, Suite 600<br>
  San Francisco, CA 94107<br>
  <abbr title="Phone">P:</abbr> (123) 456-7890
</address>

<address>
  <strong>Full Name</strong><br>
  <a href="mailto:#">first.last@example.com</a>
</address>


<%= link_to 'Go back to the hospital list', hospitals_path %>

app/views/users/new.html.erb
<h1>Sign up for our site!</h1>


<%= form_for @user do |f| %>
  Name <%= f.text_field :name, placeholder: "create your user name" %><br />
  Email <%= f.text_field :email, placeholder: "enter your email address" %><br />

  <%= f.password_field :password, placeholder: "create a password" %><br />
  <%= f.password_field :password_confirmation, placeholder: "re-enter a password" %>

  <%= f.submit "Create your Account", class: "btn btn-primary btn-large" %>

<% end %>

<%= link_to "Go back to the main page!", users_path %>






  

app/views/users/reactive.html.erb
<%= form_for @user do |f| %>
	<%= f.check_box :is_active %>
	

	<%= f.submit "Reactivate Me" %>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <h1><%= @user.name %></h1>
</p>

<p>
  <strong>Email:</strong>
  <h1><%= @user.email %></h1>
</p>




<p>If you want to edit your account information, please click 'Edit' button below</p>
<%= link_to 'Edit Account', edit_user_path(@user) %> <br />




<h1>Go to your check box to save your hospital selection</h1>

<%= link_to 'Check Box', pairings_path %><br />





<%= link_to 'Go back to the main page!', users_path %><br />