config/routes.rb
Rails.application.routes.draw do
  resources :users
  
  resource :session, only:[:new, :create, :session_path, :destroy]
  resources :hospitals

  resources :pairings

end

app/models/hospital.rb
class Hospital
  include Mongoid::Document
   
  field :name, type: String 
  field :practice_field, type: String
  field :location, type: String
  field :benefit, type: String 
  
  has_many :pairings

 end 



# 	# Bring back an array of hospitals
#   def hospitals
#   	Hospital.find hospital_ids
#   end

# #   # Bring back an array of all hospital IDs
#   def hospital_ids
#   	self.user_hospitals.map(&:hospital_id)
#   end

# #   # Update hospital IDs for this user
#   def hospital_ids=(list)
#   	self.user_hospitals.destroy
#   	list.each do |hospital_id|
#   		unless hospital_id.blank?
#   			self.user_hospitals.create(hospital_id: hospital_id)
#   		end
#   	end
#   
# end
#---------------------------------------------------

app/controllers/hospitals_controller.rb
 class HospitalsController < ApplicationController
before_action :check_user, only: [:new, :create, :edit, :update, :destroy]



  # def index
  #   @hospitals = Hospital.order ("hospital_name")
  # end 

def index
# @hospitals = Hospital.order("location", "name")

  my_hospital_filter = params[:hospitalfilter]
  case my_hospital_filter
  when "showall"
  @hospitals = Hospital.all

when "name"
  @hospitals =Hospital.where(:name => "name")
  @hospitals = Hospital.all.order("name ASC")
  
  
when "location"
  @hospitals = Hospital.where(:location => "location")
  @hospitals = Hospital.all.order("location ASC")
  
when "primary_care"
  @hospitals = Hospital.where(:practice_field => "primary_care")

when "registered_nurse"
  @hospitals = Hospital.where(:practice_field => "registered_nurse")

when "state"
  @hospitals = Hospital.where(:benefit => "state")

when "federal"
  @hospitals =Hospital.where(:benefit => "federal")

    else
  @hospitals = Hospital.all
  end 

  end

  def show
    @hospital = Hospital.find(params[:id]) 
  end

  def new
    @hospital = Hospital.new
  end

  def create 
    @hospital = Hospital.new(params.require(:hospital).permit(:name, :practice_field, :location, :benefit))
    if @hospital.save
      redirect_to hospitals_path
    else
      render 'new'
    end
  end

  def edit
    @hospital = Hospital.find(params[:id])
  end

  def update
    @hospital = Hospital.find(params[:id])
    if @hospital.update_attributes(hospital_params)
      redirect_to hospitals_path
    else
      render 'edit'
    end
  end


  

  def destroy
    @hospital = Hospital.find(params[:id])
    @hospital.destroy
    redirect_to hospitals_path
  end

  def hospital_params
    params.require(:hospital).permit(:name, :practice_field, :location, :benefit)

  end


private
  def check_user
    if ! current_user 
      redirect_to new_session_path
    end 
  end 
end 

app/views/hospitals/index.html.erb
<h1>Hospital List in Health Care Shortage Area</h1>
<p>
  <div class="link">
  <lnk class="link-md-4"><%= link_to "Show All", hospitals_path(hospitalfilter:"showall") %>
  <lnk class="link-md-1"><%= link_to "By Hospital Name Only", hospitals_path(hospitalfilter:"name") %>
  <lnk class="link-md-1"><%= link_to "By City Only", hospitals_path(hospitalfilter:"location") %>
<lnk class="lnk-md-1"><%= link_to "By Primary Care Only", hospitals_path(hospitalfilter:"primary_care")%>
<lnk class="lnk-md-1"><%= link_to "By Registered Nurse Only", hospitals_path(hospitalfilter:"registered_nurse")%>
<lnk class="lnk-md-1"><%= link_to "By State Gov Benefit Only", hospitals_path(hospitalfilter:"state") %>
<lnk class="lnk-md-1"><%= link_to "By Federal Gov Benefit Only", hospitals_path(hospitalfilter:"federal")%>
  
  <br>
</p>

  <ul>
<% @hospitals.each do |h| %>
  <li>
    <strong> <%= h.name %> </strong> 
    [<%= h.name %>]
    <lnk class="lnk-md-4"><%= link_to "Click here for more information", hospital_path(h) %>
  </li>

<% end %>
</ul>


</div>

app/views/hospitals/new.html.erb
<h1> Save this hospital on your list </h1>


<%= render 'form' %>

<%= form_for @hospital do |f| %>
  Name: <%= f.select :name, name_array() %>
  Practice_field: <%= f.select :practice_field, practice_field_array () %>
  Location: <%= f.select :location, location_array () %>
  Benefit: <%= f.select :benefit, benefit_array () %>
<%= f.submit " Submit" %>

<%= link_to "", pairings_path %>

<% end %>

<%= link_to "Back to the hospital list", hospitals_path %>

app/views/hospitals/show.html.erb
<h1><%= @hospital.name %></h1>
<h1><%= @hospital.practice_field %></h1>
<h1><%= @hospital.location %></h1>
<h1><%= @hospital.benefit %></h1> 

<p1>The hospital you have chosen is <%= @hospital.name %>, in the city of <%= @hospital.location %>, practice field is <%= @hospital.practice_field %>, and the current available government benefit is <%= @hospital.benefit %> option. </p1>


<p>To select this hospital on your list, please click the 'Check Box' link below</p2>
<%= link_to "Check Box", pairings_path(hospital_id: @hospital.id),method: :post %><br>



<%= link_to "Back to the list!", hospitals_path %>